# Experiment Details:
# Hyperparameter optimization for TTLM model trained on Shakespeare dataset

preambles:
  glong:   
    - "#!/bin/bash"
    - "#SBATCH --output=slurm/slurm-%j.out"
    - "#SBATCH --error=slurm/slurm-%j.err"   
    - "#SBATCH --partition=long"
    - "#SBATCH --gres=gpu:rtx8000:1"
    - "#SBATCH --mem=64G"
    - "#SBATCH --cpus-per-task=16"
    - "#SBATCH --nodes=1"
    - "source /home/mila/m/marawan.gamal/scratch/ptn/.venv/bin/activate"

group:
  name: "main"
  type: parallel
  jobs:
    - group:
        type: sweep
        preamble: glong
        sweep:
          lr: [5e-3]
          pos_func: ["abs", "exp"] 
          rank: [32, 64, 128, 256]
        sweep_template:  "python scripts/langauge_modelling/train_language.py --model ttlm --batch_size 64 --seq_len 16 --epochs 50 --sample_freq 24 --lr {lr} --lm_head_rank {rank} --lm_head_pos_func {pos_func} --bit_size 8 --n_bits_per_token 4 --tags HPO 8P4"
